### ISSUE TITLE
Context manager clarification

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/pyasdf#107]
Just out of curiosity, why is the current syntax for the context manager:

```python
ff = AsdfFile(tree)
with ff.write_to("example.asdf"):
    pass
```

Would it not make sense for it to be:

```python
with AsdfFile(tree) as ff:
    ff.write_to("example.asdf")
```

? What is the purpose of using ``write_to`` as a context manager?:

```python
with ff.write_to("example.asdf"):
    pass
```

**Comment by mdboom** [comment]
This is somewhat historical (when you create an AsdfFile, it may not have an underlying file object and therefore there is nothing to close).  It should probably just be cleaned up in the docs/tests and elsewhere.
