### ISSUE TITLE
Inconsistent naming of read/write_to?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/pyasdf#109]
At the moment, the methods for reading and writing are ``read`` and ``write_to``. These seem inconsistent, and I wonder if it should be either ``read_from/write_to`` or ``read/write``? (the latter would be my preferred choice).

**Comment by mdboom** [comment]
I think I'd prefer `read_from/write_to` to avoid confusion with the Python built-in file `read/write` (which function rather differently.  But I agree the `read/write_to` is inconsistent.

**Comment by mdboom** [comment]
I'll make a PR for this once some of the pending ones are closed (or this just bound to be tons of merge conflicts).
