### ISSUE TITLE
HDF5

### ISSUE THREAD

**Issue by rossant** [spacetelescope/pyasdf#150]
I suppose you considered using HDF5, but decided not to. I would be interested in knowing the reasons why you chose to design a new format over using HDF5. What were the limitations of HDF5 for your use-cases? It might also be a good idea to put those reasons on the documentation, as I'm sure other people would be interested as well.

**Comment by mdboom** [comment]
See the paper: http://dx.doi.org/10.1016/j.ascom.2015.06.004

(This paper is soon to be referenced from the standard.  See: spacetelescope/asdf-standard#93).

**Comment by embray** [comment]
Given that this isn't the place (but there isn't a place to begin with) I wonder if it wouldn't make sense to set up a mailing list for ASDF discussion.  It'll probably be fairly low traffic for now but at least that will be a place for it to go.
