### ISSUE TITLE
add support for custom extensions in `helpers` functions

### ISSUE THREAD

**Issue by nden** [spacetelescope/pyasdf#163]
I'd like to use the pyasdf testing infrastructure with custom extensions, specifically to test roundtripping.
I've looked into adding  the `extensions` keyword to the `assert_roundtrip_tree` function (calls to `AsdfFile()` and `AsdfFile.open`) but this doesn't seem to be sufficient as the type_index is not updated with the custom types.
Would it be easy to add this functionality?

**Comment by mdboom** [comment]
Definitely a good thing to add.  I would have expected passing the extensions to `AsdfFile` and `AsdfFile.open` to be sufficient though.  Let me look into why it's not working...

**Comment by mdboom** [comment]
I set up #164 -- more or less like you suggested -- and wrote a test that appears to work.  Does that work for you?  If not, let me know what you're doing -- the extension stuff is newish so I wouldn't be surprised if there's a sharp corner.

**Comment by mdboom** [comment]
Oh, and by the way -- just to confirm we aren't duplicating effort:  I'm working on wrapping gwcs.WCS and gwcs.CoordinateFrame etc.  Are you doing this for something else?

**Comment by nden** [comment]
No, I am not wrapping those. I am writing the types for the selector models.
The way I set it up for now is the schemas are still in asdf-standard and the types are in gwcs.
I'll post a PR shortly and tests this PR.

I also have several models which will live in assign_wcs and so will need to have their types and schemas there as well.

So I'm wondering if the types for gwcs.WCS and gwcs.CoordinateFrame should also be in gwcs. In which case pyasdf will not have a dependence on gwcs.

**Comment by mdboom** [comment]
That's a good question.  I think we want the schemas in asdf-standard -- WCS is one of the main drivers for ASDF, so it would be selling ASDF short to not have them defined there.  As to where to put the reader/writer code I'm having trouble coming up with a really strong argument either way.  As of this yesterday, pyasdf can use libraries as a "soft dependency" -- i.e. it doesn't have to depend on gwcs unless someone loads a file with wcs info in it.  But I guess I fall down on them living in gwcs -- with gwcs being still under development, it might be easier to have all of the ASDF interface code there as well as they may need to be updated together.

**Comment by nden** [comment]
Agreed that schemas should be in asdf-standard. I have no strong opinion about the readers/writers, especially now that gwcs is not a hard dependence. And gwcs will probably end up in astropy. So let's keep things as they are until we have a solid reason to change them. I still have to complete the process and see how the WCS object is to be written to a file (asdf or fits).

**Comment by nden** [comment]
Closed by #164
