### ISSUE TITLE
UserWarning about BuiltinExtension is not very useful

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pyasdf#694]
First of all, this warning does not make sense. This file was created back in 2018, while the `asdf` version I have installed is from `master` as of yesterday (2019-08-26). Secondly, there is nothing I can do about it, as I did not generate this file and in the real world, user probably got the file from some archive and can't remake it either. So, what is this warning for? Can this be silenced by #565 ?
```
asdf/asdf.py:202: UserWarning: File 'imaging_wcs.asdf' was created with
extension 'asdf.extension.BuiltinExtension' from package asdf-2.2.0.dev1606,
but older version asdf-2.1.2a1.dev198+gb67cb02 is installed
```

**Comment by drdavella** [comment]
I think the option you want might be ignore_version_mismatch.

**Comment by jdavies-st** [comment]
My workflow for always making sure my dev checkout of a repo has the tags:
```
git fetch upstream
```
^ gets all branches and tags.

**Comment by pllim** [comment]
I don't want all the branches. 😉
